name: autofix.ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo fmt
        run: cargo fmt

      - uses: autofix-ci/action@7a166d7532b277f34e16238930461bf77f9d7ed8
        with:
          commit-message: "chore: apply automatic fixes"
